### ISSUE TITLE
Determine release workflow

### ISSUE THREAD

**Issue by twolfson** [uber/image-diff#16]
Since I no longer have push rights to this repo and there is a PR that is nearing completion, we should figure out a workflow for pushing new releases. My proposal is:

- Use `foundry` for `git commit`, `git tag`, `git push`, `git push --tags`, and `npm publish` as was done originally
    - To make this straightforward, we can encapsulate it in a `release.sh` (e.g. `./release.sh 1.1.0`)
    - https://github.com/twolfson/foundry
- I am open to submitting PRs that include documentation and CHANGELOG updates if someone is alright with running `./release.sh` to publish it

/cc @Raynos @mlmorg

**Comment by twolfson** [comment]
Any word on this? PR #15 is more/less ready and we should get this sorted out =/

**Comment by mlmorg** [comment]
Sounds reasonable. I'm also happy to update the changelog too. We'll need to update the npm collaborators.

**Comment by twolfson** [comment]
Yea, definitely. I will take a look at adding a PR for this workflow by the end of this weekend. Who should I update the collaborators to?
