### ISSUE TITLE
Don't generate a diff image if there's no difference

### ISSUE THREAD

**Issue by mike-engel** [uber/image-diff#27]
As of right now, unless I have it configured wrong, an image will be created regardless if whether it's different or not.

```javascript
imageDiff({
  actualImage: 'one.png',
  expectedImage: 'two.png',
  diffImage: 'diff.png'
}, function (err, imagesAreSame) {
  // If one.png and two.png are the same, a blank png gets created regardless
})
```

It would be nice, if in the example above, if one and two were the same, no image was created and saved to the system.

Reading through the source, it looks like this might be an imagemagick issue. Maybe not.

**Comment by twolfson** [comment]
Yep, I don't think this is possible with imagemagick; either we provide an outfile or we don't (and ignore stdout/stderr). Can you explain your use case more? Typically people want consistent behavior for a low level library like this =/

**Comment by mike-engel** [comment]
I'm currently writing a CLI tool to take a bunch of screenshots on various webpages, and then compare them against a set of base images to catch any visual regressions from CSS/HTML changes. It's misleading to me to output an image to the `diff` directory, when there's actually no diff. I'm taking care of this on my end by watching for `imagesAreSame` and deleting it if they are the same, but I thought it would be nice to have an option here to not produce a blank image with no diff. 

Sorry if that doesn't make sense, it's early :smile:

**Comment by twolfson** [comment]
Ah, alright. Thanks for the clarification. Since there is a workaround and no easy/performant support, I think it's prob best to close this issue.

@mlmorg Can we close this issue?

**Comment by twolfson** [comment]
Thanks @mlmorg =)
