### ISSUE TITLE
Get % Difference?

### ISSUE THREAD

**Issue by skiplist** [uber/image-diff#39]
Is there a way to know the % difference?  Right now there is only a boolean true/false to know if it is different at all, but it would be very helpful to know to what % difference the images are.

**Comment by twolfson** [comment]
We should be able to add a new function or option to expose that. I think a new function would be ideal so we can keep our types consistent. I will whip up a PR to get your feedback.

**Comment by twolfson** [comment]
Alright, I have created a branch with my proposed content. Before I submit it as a PR though, I want to verify it will work for you. Can you look over the README changes here?

https://github.com/twolfson/image-diff/tree/dev/add.result.callback.sqwished#imagediffgetfullresultoptions-cb

**Comment by skiplist** [comment]
wow!  that was fast!

Yes, that's perfect.  Looks to be exactly what we need.  Thank you.

**Comment by twolfson** [comment]
Yep, it should be the new method. Nice catch :+1: I will open a PR shortly

**Comment by twolfson** [comment]
Alright, PR #40 has been opened up
